"""
Dispute Report generator.

Takes extraction + comp analysis data and produces:
1. A Markdown dispute report (human-readable summary)
2. A PDF version of that report (via ReportLab)

The report is the deliverable for Phase 1 — it summarizes the finding,
lists the comps, and lays out the legal grounds for appeal.
"""

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

from config import settings


REPORT_TEMPLATE = """# FairShare Property Assessment Dispute Report

**Generated:** {{ generated_at }}
**Report ID:** {{ report_id }}

---

## Subject Property

| Field | Value |
|---|---|
| Parcel ID | {{ parcel_id or "Not detected" }} |
| County | {{ county or "Unknown" }} |
| Owner | {{ owner_name or "Not detected" }} |
| Address | {{ property_address or "Not detected" }} |
| Property Class | {{ property_class or "Not detected" }} |
| Acreage | {{ "%.2f"|format(acreage) if acreage else "Not detected" }} acres |
| Tax Year | {{ tax_year or "Not detected" }} |
| Appraised Value | {{ "$%s"|format("{:,.0f}".format(appraised_value)) if appraised_value else "Not detected" }} |
| **Assessed Value** | **{{ "$%s"|format("{:,.0f}".format(assessed_value)) if assessed_value else "Not detected" }}** |
| Homestead Exempt | {{ "Yes" if homestead_exempt else "No" }} |
| Current Use Enrolled | {{ "Yes" if current_use_enrolled else "No" }} |

---

## Assessment Analysis

**Assessment Ratio Applied:** {{ "%.0f%%"|format(ratio * 100) }} ({{ property_class or "Standard" }})

**Median Comp Appraised Value:** {{ "$%s"|format("{:,.0f}".format(median_comp_appraised)) if median_comp_appraised else "N/A" }}

**Expected Assessed Value:** {{ "$%s"|format("{:,.0f}".format(expected_assessed)) if expected_assessed else "N/A" }}

**Over-Assessment:** {% if overassessment_pct is not none %}{{ "%.1f%%"|format(overassessment_pct * 100) }}{% else %}N/A{% endif %}

### Finding

{% if is_flagged %}
> **APPEAL RECOMMENDED** — This property appears over-assessed by {{ "%.1f%%"|format(overassessment_pct * 100) }}, exceeding the 15% threshold for a Board of Equalization appeal.
{% else %}
> Assessment appears within acceptable range. Appeal may not succeed based on current comp data.
{% endif %}

{{ summary }}

---

## Comparable Sales ({{ comp_count }} comps)

{% if comps %}
| Parcel ID | Address | Appraised Value | Acreage | $/Acre | Source |
|---|---|---|---|---|---|
{% for c in comps %}
| {{ c.parcel_id }} | {{ c.address or "—" }} | {{ "$%s"|format("{:,.0f}".format(c.appraised_value)) }} | {{ "%.1f"|format(c.acreage) if c.acreage else "—" }} | {{ "$%s"|format("{:,.0f}".format(c.price_per_acre)) if c.price_per_acre else "—" }} | {{ c.data_source }} |
{% endfor %}
{% else %}
*No comparable sales data available. Manual research required.*
{% endif %}

---

## Legal Grounds for Appeal

The following Alabama statutes support this appeal:

- **§40-7-25.3** — Current Use valuation for agricultural land (use-value vs. market-value assessment)
- **Act 2013-295** — Agricultural exemption framework
- **§40-3-1 through §40-3-29** — Board of Equalization appeal procedures
- **§40-7-1** — Annual assessment requirement; county must use fair market value

### Appeal Deadline

Alabama Board of Equalization appeals must be filed within **30 days** of receiving the assessment notice. Do not delay.

---

## Next Steps

{% if is_flagged %}
1. **Review this report** with supervising counsel
2. **Authorize FairShare** to draft and file the appeal letter
3. **Sign authorization** — FairShare handles everything from here
4. **Wait for BOE decision** — typically 60–120 days
5. **Pay success fee** of 20–25% only if we win
{% else %}
1. **Second opinion** — if you believe the assessment is still wrong, request manual review
2. **Gather additional evidence** — recent comparable sales in your specific area
3. **Contact FairShare** if your situation changes or new assessment notices arrive
{% endif %}

---

*This report was generated by FairShare's AI-assisted analysis system and reviewed under the supervision of licensed Alabama counsel. It is not legal advice. FairShare is not a law firm.*

*FairShare | Huntsville, Alabama | "We fight your bills. If we don't save you money, you pay $0."*
"""


def _render_markdown(context: dict) -> str:
    env = Environment(autoescape=False)
    template = env.from_string(REPORT_TEMPLATE)
    return template.render(**context)


def _markdown_to_pdf(markdown_text: str, output_path: str, context: dict):
    """Render a PDF from the report context using ReportLab."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    brand_blue = colors.HexColor("#1e3a5f")
    brand_green = colors.HexColor("#059669")
    alert_red = colors.HexColor("#dc2626")

    title_style = ParagraphStyle("Title", parent=styles["Heading1"],
                                  textColor=brand_blue, fontSize=20, spaceAfter=6)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                               textColor=brand_blue, fontSize=14, spaceBefore=12, spaceAfter=4)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                 fontSize=10, leading=14)
    flag_style = ParagraphStyle("Flag", parent=styles["Normal"],
                                 fontSize=11, leading=16, textColor=alert_red,
                                 borderColor=alert_red, borderWidth=1,
                                 borderPadding=8, backColor=colors.HexColor("#fef2f2"))
    ok_style = ParagraphStyle("OK", parent=styles["Normal"],
                               fontSize=11, leading=16, textColor=brand_green,
                               borderColor=brand_green, borderWidth=1,
                               borderPadding=8, backColor=colors.HexColor("#f0fdf4"))

    story = []

    # Header
    story.append(Paragraph("FairShare Property Assessment Dispute Report", title_style))
    story.append(Paragraph(
        f"Generated: {context['generated_at']}  |  Report ID: {context['report_id']}",
        styles["Normal"]
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=brand_blue, spaceAfter=12))

    # Subject property table
    story.append(Paragraph("Subject Property", h2_style))
    prop_data = [
        ["Field", "Value"],
        ["Parcel ID", context.get("parcel_id") or "Not detected"],
        ["County", context.get("county") or "Unknown"],
        ["Owner", context.get("owner_name") or "Not detected"],
        ["Address", context.get("property_address") or "Not detected"],
        ["Property Class", context.get("property_class") or "Not detected"],
        ["Acreage", f"{context['acreage']:.2f} acres" if context.get("acreage") else "Not detected"],
        ["Tax Year", str(context.get("tax_year") or "Not detected")],
        ["Appraised Value", f"${context['appraised_value']:,.0f}" if context.get("appraised_value") else "Not detected"],
        ["Assessed Value", f"${context['assessed_value']:,.0f}" if context.get("assessed_value") else "Not detected"],
        ["Homestead Exempt", "Yes" if context.get("homestead_exempt") else "No"],
        ["Current Use Enrolled", "Yes" if context.get("current_use_enrolled") else "No"],
    ]
    prop_table = Table(prop_data, colWidths=[2.2 * inch, 4.8 * inch])
    prop_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), brand_blue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("FONTNAME", (0, -2), (0, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(prop_table)
    story.append(Spacer(1, 12))

    # Analysis
    story.append(Paragraph("Assessment Analysis", h2_style))
    analysis_rows = [
        ["Assessment Ratio", f"{context['ratio'] * 100:.0f}%"],
        ["Median Comp Appraised Value", f"${context['median_comp_appraised']:,.0f}" if context.get("median_comp_appraised") else "N/A"],
        ["Expected Assessed Value", f"${context['expected_assessed']:,.0f}" if context.get("expected_assessed") else "N/A"],
        ["Over-Assessment %", f"{context['overassessment_pct'] * 100:.1f}%" if context.get("overassessment_pct") is not None else "N/A"],
    ]
    analysis_table = Table(analysis_rows, colWidths=[2.2 * inch, 4.8 * inch])
    analysis_table.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(analysis_table)
    story.append(Spacer(1, 10))

    # Finding callout
    if context.get("is_flagged"):
        pct = context["overassessment_pct"] * 100
        finding_text = f"APPEAL RECOMMENDED — Over-assessed by {pct:.1f}%, exceeding the 15% threshold."
        story.append(Paragraph(finding_text, flag_style))
    elif context.get("overassessment_pct") is not None:
        finding_text = "Assessment within acceptable range. Appeal may not succeed based on current comp data."
        story.append(Paragraph(finding_text, ok_style))

    story.append(Spacer(1, 6))
    if context.get("summary"):
        story.append(Paragraph(context["summary"], body_style))
    story.append(Spacer(1, 12))

    # Comps table
    story.append(Paragraph(f"Comparable Sales ({context['comp_count']} comps)", h2_style))
    comps = context.get("comps", [])
    if comps:
        comp_data = [["Parcel ID", "Address", "Appraised", "Acres", "$/Acre", "Source"]]
        for c in comps[:20]:  # cap display at 20
            comp_data.append([
                c.get("parcel_id", "")[:20],
                (c.get("address") or "—")[:35],
                f"${c['appraised_value']:,.0f}",
                f"{c['acreage']:.1f}" if c.get("acreage") else "—",
                f"${c['price_per_acre']:,.0f}" if c.get("price_per_acre") else "—",
                c.get("data_source", ""),
            ])
        comp_table = Table(comp_data, colWidths=[1.1*inch, 2.2*inch, 1.0*inch, 0.6*inch, 0.9*inch, 0.9*inch])
        comp_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), brand_blue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(comp_table)
    else:
        story.append(Paragraph("No comparable sales data available. Manual research required.", body_style))

    story.append(Spacer(1, 12))

    # Legal grounds
    story.append(Paragraph("Legal Grounds for Appeal", h2_style))
    legal_items = [
        "§40-7-25.3 — Current Use valuation for agricultural land",
        "Act 2013-295 — Agricultural exemption framework",
        "§40-3-1 through §40-3-29 — Board of Equalization appeal procedures",
        "§40-7-1 — Annual assessment; county must use fair market value",
    ]
    for item in legal_items:
        story.append(Paragraph(f"• {item}", body_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "<b>Appeal Deadline:</b> Alabama Board of Equalization appeals must be filed within "
        "<b>30 days</b> of receiving the assessment notice.",
        body_style
    ))

    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "<i>This report was generated by FairShare's AI-assisted analysis system under the "
        "supervision of licensed Alabama counsel. Not legal advice. FairShare is not a law firm.</i>",
        ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8,
                       textColor=colors.gray)
    ))
    story.append(Paragraph(
        '<i>FairShare | Huntsville, Alabama | "We fight your bills. If we don\'t save you money, you pay $0."</i>',
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
                       textColor=brand_blue)
    ))

    doc.build(story)


def generate_report(dispute_id: int, extraction: dict, analysis: dict) -> dict:
    """
    Generate the dispute report (Markdown + PDF).
    Returns dict with paths to both files.
    """
    settings.ensure_dirs()

    report_id = f"FS-{dispute_id:05d}"
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    context = {
        "report_id": report_id,
        "generated_at": generated_at,
        "parcel_id": extraction.get("parcel_id"),
        "county": extraction.get("county"),
        "owner_name": extraction.get("owner_name"),
        "property_address": extraction.get("property_address"),
        "property_class": extraction.get("property_class"),
        "acreage": extraction.get("acreage"),
        "tax_year": extraction.get("tax_year"),
        "appraised_value": extraction.get("appraised_value"),
        "assessed_value": extraction.get("assessed_value"),
        "homestead_exempt": extraction.get("homestead_exempt", False),
        "current_use_enrolled": extraction.get("current_use_enrolled", False),
        **analysis,
    }

    # Markdown
    md_text = _render_markdown(context)
    md_path = os.path.join(settings.report_dir, f"{report_id}.md")
    with open(md_path, "w") as f:
        f.write(md_text)

    # PDF
    pdf_path = os.path.join(settings.report_dir, f"{report_id}.pdf")
    _markdown_to_pdf(md_text, pdf_path, context)

    return {"report_id": report_id, "md_path": md_path, "pdf_path": pdf_path, "context": context}
